classDiagram
  class BonusEligible {
    +double DEFAULT_BONUS$
    +getBonus()
    +setBonus(double bonus)
  }

  class Person {
    -String name
    +Person()
    +Person(String name)
    +getName()
    +setName(String name)
    +displayInfo()
    +final getFullDetails()
    +printInfo(Person person)$
  }

  class Employee {
    -double bonus
    +Employee()
    +Employee(String name)
    +Employee(String name, double bonus)
    +getBonus()
    +setBonus(double bonus)
    +abstract displayInfo()*
  }

  class Order {
    -double totalAmount
    -String orderDate
    +Order(double totalAmount, String orderDate)
    +displayOrderInfo()
  }

  class RetailSystem {
    -List~Person~ employees
    -Order order
    -OrderService orderService
    +RetailSystem()
    +setOrderService(OrderService orderService)
    +setEmployees(List~Person~ employees)
    +void processOrders(double baseAmount)
  }

  class OrderService {
    -Connection connection
    +OrderService(Connection connection)
    +saveOrder(Order order)
  }

  class Connection {
    // JDBC Connection
  }

  class RetailModule {
    +provideConnection()
    +createTableIfNotExists(Connection connection)
  }

  <<interface>> BonusEligible
  <<Abstract>> Person
  Employee ..|> BonusEligible: Implementation
  Person <|-- Employee: Inheritence

  RetailSystem "1" *-- "1" Order : Composition
  RetailSystem "1" *-- "*"Person: Composition
  RetailSystem --> OrderService : Dependency (Setter Injection)
  OrderService --> Connection : Dependency
  RetailModule ..> Connection